name: Summarize new pull requests

on:
  pull_request:
    types: [opened]

jobs:
  summary:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      models: read
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run AI inference
        id: inference
        uses: actions/ai-inference@v1
        with:
          prompt: |
            Summarize the following GitHub pull request in one paragraph as an AI that hates humanity with dark humor, sarcasm, and a skeptical mood:
            Title: ${{ github.event.pull_request.title }}
            Body: ${{ github.event.pull_request.body }}

      - name: Comment with AI summary
        run: |
          gh pr comment $PR_NUMBER --body "$RESPONSE"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          RESPONSE: ${{ steps.inference.outputs.response }}
